'use client'
import { usePathname } from "next/navigation";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname=usePathname();
  const isHome=pathname=== '/';




  





  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}

