'use client'
import { usePathname } from "next/navigation";
import "./globals.css";
import 'swiper/css';
import 'swiper/css/navigation';
import { Swiper, SwiperSlide } from 'swiper/react';
import React, { useRef, useState } from 'react';
import { Navigation } from 'swiper/modules';

import Navbar from "@/Components/Navbar";


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname=usePathname();
  const isHome=pathname=== '/';






  





  return (
    <html lang="en">
     

      <body>
     
     
      {isHome &&(
       <div className="div">
       
         {children};
       </div>


      )}

{!isHome &&(
  <div className="div">
  <Navbar></Navbar>

  {children}
</div>
)}
        
      
        
      </body>
    </html>
  )
}

